# Change the prefix key from Ctrl+b to Ctrl+a (optional, but very popular)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable mouse support (clicking tabs, resizing panes)
set -g mouse on

# Start windows and panes indexing at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Fix terminal colors inside tmux
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Cc=\E]12;%p1%s\a"
